---
# Flushing all handlers ensures that dehydrated and nginx are properly set up before proceeding 
# with the installation. Check deploy-clickhouse-proxy.yml to see the dehydrated setup
# 
# This playbook generates new nginx rules that depends on the certificate file from dehydrated, 
# so if we restart nginx before dehydrated is properly set up this playbook will crash and 
# it will require manual intervention. 
#
# See: https://github.com/ooni/devops/pull/235#discussion_r2052289154
- name: Flush all handlers now
  meta: flush_handlers

- name: Allow traffic on port 9000
  tags: clickhouse-proxy
  blockinfile:
    path: /etc/ooni/nftables/tcp/9000.nft
    create: yes
    block: |
      add rule inet filter input tcp dport 9000 counter accept comment "clickhouse"
  notify:
    - reload nftables  

- name: Allow traffic on port 9100
  tags: prometheus-proxy
  blockinfile:
    path: /etc/ooni/nftables/tcp/9100.nft
    create: yes
    block: |
      add rule inet filter input tcp dport 9100 counter accept comment "node exporter"
  notify:
    - reload nftables  

- name: Create the modules-enabled directory if not exists
  tags: webserv
  ansible.builtin.file:
    path: /etc/nginx/modules-enabled
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Add stream nginx config
  tags: webserv
  template:
    src: templates/99-stream.conf
    dest: /etc/nginx/modules-enabled/99-stream.conf
    mode: 0755
    owner: root
  notify:
    - reload nginx
    - restart nginx
