tls_cert_dir: /var/lib/dehydrated/certs

# Fastpath user
fastpath_user: fastpath
fastpath_home: "/opt/{{ fastpath_user }}"

# Fastpath settings
# TODO Update this to the actual clickhouse host when we have migrated it 
clickhouse_url: "clickhouse://default:default@clickhouse-server:9000"