---
- name: Deploy clickhouse proxy
  hosts:
    - clickhouseproxy.dev.ooni.io
    - clickhouseproxy.prod.ooni.io
  become: true
  roles:
    - role: bootstrap
    - role: dehydrated
      vars: 
        ssl_domains: 
          - "{{ inventory_hostname }}"
        tls_cert_dir: /var/lib/dehydrated/certs
    - role: clickhouse_proxy
      vars:
        clickhouse_url: "{{'clickhouse1.prod.ooni.io' if inventory_hostname == 'clickhouseproxy.prod.ooni.io' else 'clickhouse3.prod.ooni.io'}}"
        clickhouse_port: 9000
        clickhouse_proxy_public_fqdn: "{{ inventory_hostname }}"
    - role: prometheus_node_exporter
      vars:
        node_exporter_port: 9100
        node_exporter_host: "0.0.0.0"
        prometheus_nginx_proxy_config: 
          - location: /metrics/node_exporter
            proxy_pass: http://127.0.0.1:9100/metrics
